# Generated by Django 5.2.16 on 2026-07-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_pagevisit_duration_sec'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('x', 'X'), ('linkedin', 'LinkedIn')], db_index=True, max_length=16)),
                ('lang', models.CharField(blank=True, default='', max_length=2)),
            ],
            options={
                'verbose_name': 'Somejakoklikkaus',
                'verbose_name_plural': 'Somejakoklikkaukset',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
